# Generated by Django 5.0 on 2023-12-20 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/', verbose_name='Image')),
                ('title', models.CharField(max_length=199, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('need_to_seen_by', models.IntegerField(choices=[(1, 'Every Superusers'), (2, 'Every Admins'), (3, 'Specific User'), (4, 'Some Multiple Users')], verbose_name='Need To Seen By')),
                ('remove_after_seen', models.BooleanField(default=True, verbose_name='Remove After Seen')),
                ('seen_by', models.ManyToManyField(related_name='seen_by', to=settings.AUTH_USER_MODEL, verbose_name='Seen By')),
                ('specific_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Specific User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
