# Generated by Django 5.0 on 2023-12-20 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifications_people_to_see_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_format',
            field=models.CharField(default='{title} : {text}', max_length=199),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='seen_by',
            field=models.ManyToManyField(blank=True, editable=False, null=True, related_name='seen_by', to=settings.AUTH_USER_MODEL, verbose_name='Seen By'),
        ),
    ]
