# Generated by Django 5.0 on 2023-12-20 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notifications_notification_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='specific_user',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='need_to_seen_by',
            field=models.IntegerField(choices=[(1, 'Every Superusers'), (2, 'Every Admins'), (3, 'Custom User/Users')], default=3, verbose_name='Need To Seen By'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_format',
            field=models.CharField(default='{title} : {text}', help_text='Available Options Are : image, title, text, seen_by, need_to_seen_by, people_to_see, remove_after_seen', max_length=199, verbose_name='Notification Format To Show In Admin'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='people_to_see',
            field=models.ManyToManyField(blank=True, help_text="This Field Must Be Setted If You Setted The Field 'Need To Seen By' To 'Custom User/Users'", null=True, related_name='people_to_sees', to=settings.AUTH_USER_MODEL, verbose_name='People To See Notifications'),
        ),
    ]
